[package]
name = "Rust-LLM"
version = "0.1.0"
edition = "2024"

[dependencies]
async-openai = "0.28.0"
base64 = "0.22.1"
dotenv = "0.15.0"
gemini_client_rs = "0.2.0"
serde_json = "1.0.140"
tokio = "1.44.1"
